# Lightweight Python image
FROM python:3.11-slim

# Working directory inside the container
WORKDIR /app

# Copy dependencies and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY syscall-sms-relayer.py .

# [NEW] Copy the static folder containing index.html, css, js
COPY static ./static

# Create logs directory (for permissions)
RUN mkdir logs

# Start the server
CMD ["python", "syscall-sms-relayer.py"]
