FROM python:3.9-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y gcc

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy App Source
COPY syscall-heartbeat-relayer.py .
COPY static/ ./static/

# Environment variables should be injected by Docker Compose/Run
EXPOSE 8080

CMD ["python", "syscall-heartbeat-relayer.py"]
